package com.example.lolgg


fun getQueueId() : MutableMap<String, String>
{
    val queueId = mutableMapOf<String, String>()
    queueId["0"] = "사용자 설정"
    queueId["4"] = "개인 랭크"
    queueId["6"] = "자유 랭크"
    queueId["7"] = "칼바람의 나락"
    queueId["72"] = "쇼다운"
    queueId["73"] = "쇼다운"
    queueId["75"] = "헥사킬"
    queueId["76"] = "URF"
    queueId["78"] = "단일"
    queueId["83"] = "URF : Bot"
    queueId["96"] = "초월"
    queueId["98"] = "헥사킬"
    queueId["100"] = "도살자의 다리 : 무작위"
    queueId["310"] = "Nemesis games"
    queueId["313"] = "암시장 용병"
    queueId["317"] = "수정의 상처"
    queueId["325"] = "소환사의 협곡 : 무작위"
    queueId["400"] = "소환사의 협곡"
    queueId["420"] = "솔로 랭크"
    queueId["430"] = "일반 게임"
    queueId["440"] = "자유 랭크"
    queueId["450"] = "칼바람의 나락"// 무작위
    queueId["600"] = "불의 축제"
    queueId["610"] = "암흑의 별"
    queueId["700"] = "소환사의 협곡 : 격전"
    queueId["720"] = "칼바람의 나락 : 격전"
    queueId["820"] = "뒤틀린 숲 : Bot"
    queueId["830"] = "입문 Bot"
    queueId["840"] = "초급 Bot"
    queueId["850"] = "중급 Bot"
    queueId["900"] = "URF : 무작위"
    queueId["910"] = "초월"
    queueId["920"] = "전설의 포로왕"
    queueId["940"] = "돌격! 넥서스"
    queueId["950"] = "초토화 봇"
    queueId["960"] = "초토화 봇"
    queueId["980"] = "별 수호자"
    queueId["990"] = "별 수호자"
    queueId["1000"] = "프로젝트"
    queueId["1010"] = "URF : 눈싸움 무작위"
    queueId["1020"] = "단일"
    queueId["1030"] = "오디세이"
    queueId["1040"] = "오디세이"
    queueId["1050"] = "오디세이"
    queueId["1060"] = "오디세이"
    queueId["1070"] = "오디세이"
    queueId["1300"] = "돌격! 넥서스"
    queueId["1400"] = "궁극기 주문서"
    queueId["1900"] = "URF : 선택"
    queueId["2000"] = "튜토리얼 1"
    queueId["2010"] = "튜토리얼 2"
    queueId["2020"] = "튜토리얼 3"
    //홍성희
    return queueId
}